import "@/styles/globals.css";
import type { Metadata } from "next";
import LayoutWrapper from "@/components/LayoutWrapper";
import { UserProvider } from "@/context/AuthContext";


export const metadata: Metadata = {
  title: "Amarits Admin-Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`overflow-y-hidden`}>
        <UserProvider>
          <LayoutWrapper>
            {children}
          </LayoutWrapper>
        </UserProvider>
      </body>
    </html>
  );
}
