import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Amartis Admin-Dashboard",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className=" MonoSans text-gray-900 antialiased">
        {children}
      </body>
    </html>
  );
}
