import Sidebar from "@/components/Sidebar";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { ToastContainer } from 'react-toastify'

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Amarits Admin-Dashboard",
=======
  title: "Amartis Admin-Dashboard",
>>>>>>> 4a96883b745667652b4eafa22041447faed968dc
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className="Inter overflow-y-hidden">
        <div className="flex min-h-screen bg-gray-50 text-gray-900">
          {/* Sidebar */}
          <Sidebar />
          <div className="flex-1 p-5 overflow-y-scroll h-screen">
            {children}
          </div>
          <ToastContainer />
        </div>
=======
      <body className=" MonoSans text-gray-900 antialiased">
        {children}
>>>>>>> 4a96883b745667652b4eafa22041447faed968dc
      </body>
    </html>
  );
}
